config/routes.rb
Startup::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => "resources#index"
  devise_for :users, :skip => [:sessions], controllers: {omniauth_callbacks: "omniauth_callbacks"}
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')

  resources :users, :only => [:show, :edit, :update] do
    get '/resources' => "resources#index"
    get '/destroy_facebook' => "users#destroy_facebook"
  end
  resources :resources, :except => [:destroy] do
    put '/i_want_it' => 'resources#i_want_it'
  end
  resources :events, :only => [:index, :show] do
    put '/join' => 'events#join'
  end

  resources :posts, :only => [:index, :show]
  get '/about', :to => "welcome#about"
  get '/bmca', :to => "welcome#bmca"

  namespace :admin do
    get '/dashboard' => "dashboards#index"
    get '/unconfirmed_users' => "users#unconfirmed_users"
    get '/unapproved_resources' => 'resources#unapproved_resources'
    get '/my_responsibility' => 'resources#my_responsibility'
    put '/confirm_user/:id' => "users#confirm_user"
    put '/upgrade/:id' => 'users#add_to_admin'
    resources :users
    resources :resources do
      get '/matchers' => 'resources#matchers'
      put '/match' => 'resources#match'
      get '/add_matcher' => 'resources#add_matcher'
      put '/update_matchers' => 'resources#update_matchers'
      resources :comments, :only => [:create]
    end
    resources :resource_types
    resources :admin_categories, :except => [:show]
    resources :events do
      get '/attendees' => 'event#attendees'
    end
    resources :posts
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :assets
  has_many :images
  belongs_to :user
  has_many :join_event_attendee_ships
  has_many :attendees, :class_name => User, :through => :join_event_attendee_ships
  accepts_nested_attributes_for :assets, :allow_destroy => true
  accepts_nested_attributes_for :images, :allow_destroy => true

  geocoded_by :address
  validates_presence_of :name, :description, :address
  after_validation :geocode

  scope :available, where(["start_time > ?", Time.now])
  scope :opened, where(:is_open => true)

  def join(user)
    JoinEventAttendeeShip.create!(:user_id => user.id, :event_id => self.id)
  end

  def first_image
    return false if self.images.count == 0
    self.images.first.image
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin!

  def new
    @event = Event.new
    #2.times do
      #@event.assets.build
      #@event.images.build
    #end
  end

  def create
    @event = current_user.events.build(params[:event])

    if @event.save
      flash[:notice] = I18n.t('action.create_successful')
      redirect_to admin_event_path(@event)
    else
      render :action => "new"
    end
  end

  def index
    if params[:available]
      @events = Event.available.paginate(:page => params[:page])
    else
      @events = Event.paginate(:page => params[:page])
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update_attributes(params[:event])
      flash[:notice] = I18n.t('action.update_successful')
      redirect_to admin_event_path(@event)
    else
      render :action => "edit"
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:warning] = I18n.t('action.destroy_successful')
    redirect_to admin_events_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :only => [:join]

  def index
    @events = Event.available.opened.paginate(:page => params[:page])
  end

  def show
    @event = Event.find(params[:id])
    @title = @event.name
  end

  def join
    @event = Event.find(params[:event_id])
    @event.join(current_user)
    flash[:notice] = I18n.t('event.message.join_successful')
    EventMailer.confirm(current_user, @event.name).deliver
    redirect_to @event
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def show_google_map(lat, lon)
    "http://maps.google.com/maps/api/staticmap?center=#{lat},#{lon}&zoom=13&markers=#{lat},#{lon}&size=300x300&sensor=false"
  end

  def link_to_google_map(lat, lon)
    "http://maps.google.com/maps?q=#{lat},+#{lon}"
  end

  def show_join_button(event, user)
    if event.attendees.include?(user)
      content_tag(:button, I18n.t('event.action.joined'), :class => 'btn btn-danger btn-large', :disabled => true, :style => 'width: 100%')
    else
      link_to I18n.t('event.action.count_me_in'), event_join_path(@event), :method => :put, :class => 'btn btn-primary btn-large'
    end
  end

end

app/views/admin/events/_form.html.slim
-if f.error_notification
  div.alert.alert-error.fade.in
    a.close data-dismiss="alert" href="#" &times;
    = f.error_notification
section.event.form-inputs
  = f.input :name, :label => I18n.t('event.attributes.name'), :input_html => {:class => 'span8'}
  = f.input :description, :label => I18n.t('event.attributes.description'), :input_html => {:rows => 20, :cols => 10, class: 'span8'}
  = f.input :start_time, :label => I18n.t('event.attributes.start_time')
  = f.input :end_time, :label => I18n.t('event.attributes.end_time')
  = f.input :address, :label => I18n.t('event.attributes.address'), :input_html => {:class => 'span8'}
  = f.input :price, :label => '費用', :input_html => {:class => 'span8'}
  = f.input :is_open, :label => '是否發佈到前台'
div.form-actions
  = f.submit I18n.t('action.save'), :class => 'btn btn-primary'

app/views/admin/events/edit.html.slim
head
  h1= @event.name
= simple_form_for @event, :url => admin_event_path(@event), :html => { :class => 'form-horizontal' } do |f|
  = render :partial => 'form', :locals => {:f => f}
= link_to I18n.t('event.back_to_index'), admin_events_path, :class => 'btn'

app/views/admin/events/index.html.slim
div.dashboard.row
  aside.span3
    div.well
      = render :partial => 'admin/dashboards/aside', :locals => { :id => 'startupo-events' }
  div.span9
    = link_to I18n.t('event.add_event'), new_admin_event_path, :class => 'btn btn-large btn-success'
    hr
    - @events.each do |event|
      div.admin-event
        div.admin-event-date
          h2= l event.start_time, :format => :long
        div.admin-event-pople
          p 已有 #{event.attendees.count} 人報名
        div.admin-event-name
          h3= link_to event.name, admin_event_path(event)
      hr
    = will_paginate @events

app/views/admin/events/new.html.slim
head.event
  h1= I18n.t('event.new')
= simple_form_for @event, :url => admin_events_path, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => 'form', :locals => {:f => f}
= link_to I18n.t('event.back_to_index'), admin_events_path, :class => 'btn'

app/views/admin/events/show.html.slim
head.event
  h1= @event.name
section.event.row
  div.span8
    table.table.table-striped.table-condensed.table-bordered.event-basic-info
      tr
        td= I18n.t('event.attributes.user')
        td.event_description= @event.user.name
      tr
        td= I18n.t('event.attributes.description')
        td.event_description= raw @event.description
      tr
        td= I18n.t('event.attributes.duration')
        td.event_description= "#{I18n.l(@event.start_time)} #{I18n.t('to')} #{I18n.l(@event.end_time)}"
    /div.event-images
      /- @event.images.each do |image|
        /= image_tag(image.image.url(:medium), :class => "image")
    div.map
      h2= I18n.t('event.attributes.address')
      = @event.address
      br
      = link_to(image_tag(show_google_map(@event.latitude, @event.longitude), :id => "google-static-map"), link_to_google_map(@event.latitude, @event.longitude), :target => "_blank")
    /div.event-files
      /- @event.assets.each do |asset|
        /| 下載 :
        /= link_to " #{asset.file_file_name}", asset.file.url
  div.span4
    = link_to I18n.t('event.update_this_event'), edit_admin_event_path(@event), :class => 'btn btn-primary'
    div.attendees.well
      head
        h1 #{I18n.t('event.attributes.attendees')} #{show_badge(@event.attendees.count)}
      div.attendees
        - @event.attendees[0..10].each do |attendee|
          = link_to attendee.name, user_path(attendee)