config/routes.rb
Startup::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => "resources#index"
  devise_for :users, :skip => [:sessions], controllers: {omniauth_callbacks: "omniauth_callbacks"}
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')

  resources :users, :only => [:show, :edit, :update] do
    get '/resources' => "resources#index"
    get '/destroy_facebook' => "users#destroy_facebook"
  end
  resources :resources, :except => [:destroy] do
    put '/i_want_it' => 'resources#i_want_it'
  end
  resources :events, :only => [:index, :show] do
    put '/join' => 'events#join'
  end

  resources :posts, :only => [:index, :show]
  get '/about', :to => "welcome#about"
  get '/bmca', :to => "welcome#bmca"

  namespace :admin do
    get '/dashboard' => "dashboards#index"
    get '/unconfirmed_users' => "users#unconfirmed_users"
    get '/unapproved_resources' => 'resources#unapproved_resources'
    get '/my_responsibility' => 'resources#my_responsibility'
    put '/confirm_user/:id' => "users#confirm_user"
    put '/upgrade/:id' => 'users#add_to_admin'
    resources :users
    resources :resources do
      get '/matchers' => 'resources#matchers'
      put '/match' => 'resources#match'
      get '/add_matcher' => 'resources#add_matcher'
      put '/update_matchers' => 'resources#update_matchers'
      resources :comments, :only => [:create]
    end
    resources :resource_types
    resources :admin_categories, :except => [:show]
    resources :events do
      get '/attendees' => 'event#attendees'
    end
    resources :posts
  end
end

app/views/admin/resources/_form.html.slim
-if f.error_notification
  div.alert.alert-error.fade.in
    a.close data-dismiss="alert" href="#" &times;
    = f.error_notification
section.resource.form-inputs
  = f.input :assign_to, :label => I18n.t('resource.attributes.assign_to'), :collection => @admins
  = f.input :state, :label => I18n.t('resource.attributes.state'), :collection => Resource::STATE.invert
  = f.input :contract_state, :label => I18n.t('resource.attributes.contract_state'), :collection => Resource::CONTRACT_STATE.invert
  = f.input :to_public, :label => I18n.t('resource.attributes.to_public')
  = f.input :title, :label => I18n.t('resource.attributes.title')
  = f.input :have_resource, :label => I18n.t('resource.attributes.have_resource')
  = f.input :find_resource, :label => I18n.t('resource.attributes.find_resource')
  - if @resource.contact
    = f.input :contact, :label => I18n.t('resource.attributes.contact')
    = f.input :phone, :label => I18n.t('resource.attributes.phone')
    = f.input :email, :label => I18n.t('resource.attributes.email')
  - else
    = f.input :contact, :label => I18n.t('resource.attributes.contact'), :input_html => { :value => current_user.name }
    = f.input :phone, :label => I18n.t('resource.attributes.phone'), :input_html => { :value => current_user.mobile }
    = f.input :email, :label => I18n.t('resource.attributes.email'), :input_html => { :value => current_user.email }
  = f.input :description, :as => :ckeditor, :label => I18n.t('resource.attributes.description')
  = f.input :privacy, :label => I18n.t('resource.attributes.privacy'), :collection => Resource::PRIVACY.invert, :as => :radio_buttons
  = f.association :resource_types, :label => I18n.t('resource.attributes.types'), :as => :check_boxes
  = f.association :cooperate_ways, :label => I18n.t('resource.attributes.cooperate_ways'), :as => :check_boxes
  = f.association :admin_categories, :label => I18n.t('resource.attributes.admin_categories'), :as => :check_boxes
div.form-actions
  = f.submit I18n.t('action.save'), :class => 'btn btn-primary'

app/views/admin/resources/_list.html.slim
table.table.table-striped.table-condensed.table-bordered
  tr
    th= I18n.t('resource.attributes.state')
    th= I18n.t('resource.attributes.assign_to')
    th= I18n.t('resource.attributes.to_public')
    th= I18n.t('resource.attributes.title')
    th= I18n.t('resource.attributes.description')
    th= I18n.t('resource.matcher.count')
  - @resources.each do |resource|
    tr
      td.resource-state
        - if resource.state == "proccessing"
          span.badge.badge-success= t resource.state
        - elsif resource.state == "pending"
          span.badge.badge-warning= t resource.state
        - elsif resource.state == "denied"
          span.badge.badge-improtant= t resource.state
        - elsif resource.state == "done"
          span.badge.badge-info= t resource.state
        - else
          span.badge= t resource.state
      - if resource.assignee
        td.resource-assignee= resource.assignee.name
      - else
        td 未指定處理人員
      td.resource-to_public= resource.to_public
      td.resource-name= link_to resource.title, admin_resource_path(resource)
      td.resource-description= simple_format resource.description
      td.reosurce-matchers
        - if resource.matchers.count <= 5
            span.badge= resource.matchers.count
        - elsif resource.matchers.count > 5 && resource.matchers.count <= 10
            span.badge.badge-success= resource.matchers.count
        - elsif resource.matchers.count > 10 && resource.matchers.count <= 50
            span.badge.badge-important= resouce.matchers.count
        - elsif resource.matchers.count > 50 && resource.matchers.count <= 100
            span.badge.badge-info= resouce.matchers.count

app/views/admin/resources/add_matcher.html.slim
article.row
  head
    h1 #{@resource.title} #{I18n.t('s')} #{I18n.t('resource.matcher.add')}
  hr
  = simple_form_for @resource, :url => admin_resource_update_matchers_path(@resource), :html => {:class => 'form-horizontal'} do |f|
    = f.association :matchers, :label => I18n.t('resource.matcher.choose_matcher'), :collection => @users, :as => :check_boxes
    = f.submit I18n.t('action.save'), :class => 'btn btn-primary'

app/views/admin/resources/edit.html.slim
head
  h1= @resource.title
= simple_form_for @resource, :url => admin_resource_path(@resource), :html => { :class => 'form-horizontal' } do |f|
  = render :partial => 'form', :locals => {:f => f}
= link_to I18n.t('resource.back_to_index'), admin_resources_path, :class => 'btn'

app/views/admin/resources/index.html.slim
div.dashboard.row-fluid
  aside.span3
    div.well
      = render :partial => 'admin/dashboards/aside', :locals => { :id => 'startupo-resources' }
  div.span9
    = render 'list'
    = will_paginate @resources

app/views/admin/resources/matchers.html.slim
article.row
  head
    h1 #{@resource.title} #{I18n.t('s')} #{I18n.t('resource.attributes.matchers')}
  hr
  = link_to I18n.t('resource.matcher.add'), admin_resource_add_matcher_path(@resource), :class => 'btn btn-primary'
  hr
  table.table.table-bordered.table-striped.table-condensed
    thead
      tr
        td= I18n.t('resource.matcher.statuses')
        td= I18n.t('resource.attributes.matcher')
        td= I18n.t('action.actions')
    tbody
    - @matchers.each do |matcher|
      tr
        td= I18n.t("resource.matcher.status.#{matcher.match_status(@resource)}")
        td= link_to matcher.name, admin_user_path(matcher)
        td #{link_to I18n.t('resource.matcher.match_it'), admin_resource_match_path(@resource, :status => 'matched', :matcher => matcher), :method => :put, :class => 'btn btn-success'} | #{link_to I18n.t('resource.matcher.deny_it'), admin_resource_match_path(@resource, :status => 'deny', :matcher => matcher), :method => :put, :class => 'btn btn-danger'} | #{link_to I18n.t('resource.matcher.contact_it'), admin_resource_match_path(@resource, :status => 'contacting', :matcher => matcher), :method => :put, :class => 'btn btn-primary'}

app/views/admin/resources/my_responsibility.html.slim
div.dashboard.row
  aside.span2
    div.well
      = render :partial => 'admin/dashboards/aside', :locals => { :id => 'startupo-my_responsibility' }
  div.span10
    = render 'list'
    =will_paginate @resources

app/views/admin/resources/new.html.slim
head.resource
  h1= I18n.t('resource.new')
= simple_form_for @resource, :url => admin_resources_path, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => 'form', :locals => {:f => f}
= link_to I18n.t('resource.back_to_index'), admin_resources_path, :class => 'btn'

app/views/admin/resources/show.html.slim
head.resource
  h1= @resource.title
hr
section.resource.row
  div.span8
    div.actions
      = simple_form_for @resource, :url => admin_resource_path(@resource), :html => {:class => 'form-inline'} do |f|
        = f.input :assign_to, :label => I18n.t('resource.attributes.assign_to'), :collection => @admins, :as => :select
        = f.submit I18n.t('resource.assign_to_admin'), :class => 'btn'
      = simple_form_for @resource, :url => admin_resource_path(@resource) do |f|
        = f.input :state, :label => I18n.t('resource.attributes.state'), :collection => Resource::STATE.invert, :as => :radio_buttons, :item_wrapper_class =>  'inline'
        = f.submit I18n.t('resource.set_state'), :class => 'btn'
    table.table.table-striped.table-condensed.table-bordered
      tr
        td= I18n.t('resource.attributes.user')
        td.resource_description= @resource.user.name
      tr
        td= I18n.t('resource.attributes.description')
        td.resource_description= simple_format @resource.description
      tr
        td= I18n.t('resource.attributes.have_resource')
        td.resource_have_resource= @resource.have_resource
      tr
        td= I18n.t('resource.attributes.find_resource')
        td.resource_find_resource= @resource.find_resource
      tr
        td= I18n.t('resource.attributes.contact')
        td.resource_contact= @resource.contact
      tr
        td= I18n.t('resource.attributes.phone')
        td.resource_phone= @resource.phone
      tr
        td= I18n.t('resource.attributes.email')
        td.resource_email= @resource.email
      tr
        td= I18n.t('resource.attributes.privacy')
        td.resource_state= @resource.privacy
      tr
        td= I18n.t('resource.attributes.types')
        td.resource_types= @resource.types
      tr
        td= I18n.t('resource.attributes.cooperate_ways')
        td.resource_cooperate_ways= @resource.ways
      tr
        td= I18n.t('resource.attributes.admin_categories')
        td.resource_admin_categories= @resource.categories
    hr
    div.comments.row
      head
        h2 處理記錄
      section.span8
        = simple_form_for [:admin, @resource, @comment] do |f|
          = f.input :content, :label => false, :placeholder => '留言', :input_html => {:rows => 3, :class => 'span8'}
          = f.submit '留言', :class => 'btn btn-success'
        - @resource.comments.each do |comment|
          div.comment.well
            div.comment-attr
              div.comment-author
                strong= comment.user_name
              div.comment-timestamp.pull-right
                small 發佈於 #{comment.created_at.strftime('%Y/%m/%d %H:%M')}
            hr
            div.content
              = simple_format comment.content
  aside.resource.span4
    div.resource.actions.well
      head
        h1= I18n.t('action.actions')
      hr
      = link_to I18n.t('action.update_this_resource'), edit_admin_resource_path(@resource), :class => 'btn btn-success'
    div.resource.matchers.well
      head
        h1= I18n.t('resource.attributes.matchers')
      hr
      table.table.table-striped.table-bordered
        thead
          tr
            td= I18n.t('resource.attributes.apply_date')
            td= I18n.t('resource.attributes.matcher')
        tbody
        - @resource.matchers.each do |matcher|
          tr
            td= matcher.match_date(@resource)
            td= link_to matcher.name, admin_user_path(matcher)
      = link_to I18n.t('action.show_more'), admin_resource_matchers_path(@resource)

app/views/admin/resources/unapproved_resources.html.slim
div.dashboard.row
  aside.span2
    div.well
      = render :partial => 'admin/dashboards/aside', :locals => { :id => 'startupo-unapproved_requests' }
  div.span10
    table.table.table-striped.table-condensed.table-bordered
      tr
        th= I18n.t('resource.attributes.title')
        th= I18n.t('resource.attributes.description')
      - @resources.each do |resource|
        tr
          td.resource_type-name= link_to resource.title, admin_resource_path(resource)
          td.resource_type-description= resource.description
    =will_paginate @resources