config/routes.rb
Startup::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => "resources#index"
  devise_for :users, :skip => [:sessions], controllers: {omniauth_callbacks: "omniauth_callbacks"}
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')

  resources :users, :only => [:show, :edit, :update] do
    get '/resources' => "resources#index"
    get '/destroy_facebook' => "users#destroy_facebook"
  end
  resources :resources, :except => [:destroy] do
    put '/i_want_it' => 'resources#i_want_it'
  end
  resources :events, :only => [:index, :show] do
    put '/join' => 'events#join'
  end

  resources :posts, :only => [:index, :show]
  get '/about', :to => "welcome#about"
  get '/bmca', :to => "welcome#bmca"

  namespace :admin do
    get '/dashboard' => "dashboards#index"
    get '/unconfirmed_users' => "users#unconfirmed_users"
    get '/unapproved_resources' => 'resources#unapproved_resources'
    get '/my_responsibility' => 'resources#my_responsibility'
    put '/confirm_user/:id' => "users#confirm_user"
    put '/upgrade/:id' => 'users#add_to_admin'
    resources :users
    resources :resources do
      get '/matchers' => 'resources#matchers'
      put '/match' => 'resources#match'
      get '/add_matcher' => 'resources#add_matcher'
      put '/update_matchers' => 'resources#update_matchers'
      resources :comments, :only => [:create]
    end
    resources :resource_types
    resources :admin_categories, :except => [:show]
    resources :events do
      get '/attendees' => 'event#attendees'
    end
    resources :posts
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  layout "admin"
  before_filter :authenticate_admin!

  def index
    @unconfirmed_users = User.unconfirmed_users.limit(10)
    @unapproved_resources = Resource.unapproved.limit(10)
    @my_responsibility = Resource.my_responsibility(current_user).limit(10)
    @events = Event.available.limit(10)
  end
end

app/views/admin/dashboards/_aside.html.slim
javascript:
  id = "##{id}"
coffee:
  jQuery ->
    $(id).addClass 'active'
ul.nav.nav-list
  li#startupo-resources
    = link_to admin_resources_path do
      = t('admin.dashboard.resources')
      = show_badge(Resource.count)
  li#startupo-unconfirmed_users
    = link_to admin_unconfirmed_users_path do
      = t('admin.dashboard.unconfirmed_users')
      = show_badge(User.unconfirmed_users.count)
  li#startupo-unapproved_requests
    = link_to  admin_unapproved_resources_path do
      = t('admin.dashboard.unapproved_requests')
      = show_badge(Resource.unapproved.count)
  li#startupo-my_responsibility
    = link_to admin_my_responsibility_path do
      = t('admin.dashboard.my_responsibility')
      = show_badge(Resource.my_responsibility(current_user).count)
  li#startupo-events
    = link_to admin_events_path(:available => true) do
      = t('admin.dashboard.events')
      = show_badge(Event.available.count)
  li#startupo-users
    = link_to '使用者列表', admin_users_path
  li#starupo-posts
    = link_to '史塔波訊息列表', admin_posts_path

app/views/admin/dashboards/index.html.slim
div.dashboard.row-fluid
  aside.span3.well
    = render :partial => 'aside', :locals => { :id => 'startupo-unconfirmed_users'}